### PR TITLE
Add compatibility with PHPUnit6.

### PR DESCRIPTION
**Pull request by fattouchsquall**
Hello,

I add a new class client for PHPUnit 6 to be compatible with, this PR is in WIP mode because i updated all test units to phpunit 6.

### CODE REVIEW

**Comment by titanrat** [comment]
Any progress with this update?

**Comment by 20uf** [comment]
I hope! ping @fattouchsquall :1st_place_medal:

**Comment by fattouchsquall** [comment]
I'll do it next week.

Le 7 juin 2017 5:14 PM, "Michael COULLERET" <notifications@github.com> a
écrit :

**Comment by titanrat** [comment]
Works only with phpunit 6.0 after this merge?

**Comment by fattouchsquall** [comment]
Nope, you can use the client you want, if you want to add another client,
you can do this: \Phake::setClient(new \Phake_Client_PHPUnit());

Bien cordialement.

*Amine FATTOUCH*
*Symfony Architect*

*Email.  amine.fattouch@gmail.com <amine.fattouch@gmail.com>*
*Github.  **https://github.com/fattouchsquall
<https://github.com/fattouchsquall>*

2017-06-13 18:10 GMT+02:00 Victor Zharikov <notifications@github.com>:

**Comment by titanrat** [comment]
Ok. Nice!
@mlively Can you rewiew?

**Comment by fattouchsquall** [comment]
Ping @mlively, can you check this PR please?

**Comment by sebastianbergmann** [comment]
@mlively Do you have an ETA for when this will make it into a release? Thanks!

**Comment by mlively** [comment]
I just released it as 3.0.0. I had a few test issues and travis-ci issues I wanted to sort out before I released it.

**Comment by 20uf** [comment]
Thanks @fattouchsquall !

**Pull request merged**
