### PR TITLE
PHPUnit 9.0 support

### PR DESCRIPTION
**Pull request by strider2038**
Addresses issue #285

### CODE REVIEW

**Comment by strider2038** [comment]
@bfeaver can you review this and merge?

**Comment by slt** [comment]
I would also like this

**Comment by pps1** [comment]
@bfeaver I can confirm that this PR solves PHPUnit 9 composer conflicts. Would it be possible to merge when you get a chance as its blocking our upgrade at this time?

**Comment by phazei** [comment]
Hey Brian / @bfeaver !  Long time ;)
I'd too like this merged

**Comment by bfeaver** [comment]
I will try and look into this tonight or this afternoon. But I didn't want to ignore you all. :)

**Comment by bfeaver** [comment]
FYI, I tagged 3.1.8 for this change.

**Comment by floverdevel** [comment]
i did a composer update but i still get an error.
does the new tag v3.1.8 should already be available?

**Comment by floverdevel** [comment]
Oh i see, on packagist it says 3.1.7 is the latest version and that the package is not auto-updated.

> This package is not auto-updated.
>
> Last update: 2020-05-09 01:36:56 UTC

https://packagist.org/packages/phake/phake

**Comment by floverdevel** [comment]
Hey all 😄 
Thank you @strider2038 for the fix 👍 
Thanks you @bfeaver for the merge 👍 
Do you know when does the 3.1.8 version will be release on packagist?

**Comment by bfeaver** [comment]
3.1.8 is updated on Packagist.

**Pull request merged**
