### PR TITLE
PHP 8.0 Support

### LINKED ISSUE #289: Method ReflectionParameter::isArray() is deprecated in PHP 8
with latest phpunit (9.4.4) and latest phake(v3.1.8)

```console
  Method ReflectionParameter::isArray() is deprecated

  at vendor/phake/phake/src/Phake/ClassGenerator/MockClass.php:611
    607▕         $type    = '';
    608▕ 
    609▕         try
    610▕         {
  ➜ 611▕             if ($parameter->isArray()) {
    612▕                 $type = 'array ';
    613▕             } elseif (method_exists($parameter, 'isCallable') && $parameter->isCallable()) {
    614▕                 $type = 'callable ';
    615▕             } elseif ($parameter->getClass() !== null) {
```

> ReflectionParameter::getClass(), ReflectionParameter::isArray(), and ReflectionParameter::isCallable() are deprecated. ReflectionParameter::getType() and the ReflectionType APIs should be used instead.

https://www.php.net/manual/en/migration80.deprecated.php

### PR DESCRIPTION
**Pull request by slt**
Resolves #289 

Avoid using ReflectionParameter isArray, isCallable & getClass
as these are depreciated.

Set minimum php version as 7.1 as ReflectionNamedType is available
as of this version

This was what was required to get Phake working with PHP8 working my project - Open to feedback

### CODE REVIEW

**Comment by garethellis36** [comment]
@mlively Hello :) Do you know if and when you will be able to review this PR? It is blocking our PHP 8 upgrade at the moment. If you have no plans or time to review and merge this, it would be good to know so that we can start the process of migrating to Mockery. Thank you :)

**Comment by mlively** [comment]
@slt I'll look at it today, it is failing tests at the moment. I just want to check those before I merge it.

**Comment by niconoe-** [comment]
All of those failures might probably come from the matrix definition to test much more combinations than previously, but it looks like it comes with unexpected behavior on the tests. 
Maybe just focusing on the deprecation removal with the modification of the MockClass.php and just adding php 7.4 and php 8.0 on travis could be ok to validate a part of it, and the matrix tests could be done in a separated PR?

**Comment by adoy** [comment]
This was also fixed by #291. This issue can be closed.

**Pull request closed without merging**
