### PR TITLE
Fix fatal error when Stubbing method having nullable return type null

### PR DESCRIPTION
**Pull request by chocopie116**
https://github.com/mlively/Phake/issues/242

### CODE REVIEW

**Comment by chocopie116** [comment]
```
$ ./vendor/phpunit/phpunit/phpunit.php
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/phpunit.xml.dist

.....S.........................................................  63 / 433 ( 14%)
................................................PHP Fatal error:  Uncaught TypeError: Return value of PhakeTest_NullableScalarTypes_PHAKE593ffbdf3db3e1::objectReturn() must be an instance of PhakeTest_A, null returned in /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code:56
Stack trace:
#0 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/tests/Phake/ClassGenerator/MockClassTest.php(818): PhakeTest_NullableScalarTypes_PHAKE593ffbdf3db3e1->objectReturn()
#1 [internal function]: Phake_ClassGenerator_MockClassTest->testStubbingNullableScalarReturnHints()
#2 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(987): ReflectionMethod->invokeArgs(Object(Phake_ClassGenerator_MockClassTest), Array)
#3 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(838): PHPUnit_Framework_TestCase->runTest()
#4 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/vendor/phpunit/phpunit/PHPUnit/Framework/TestResult in /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code on line 56

Fatal error: Uncaught TypeError: Return value of PhakeTest_NullableScalarTypes_PHAKE593ffbdf3db3e1::objectReturn() must be an instance of PhakeTest_A, null returned in /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code:56
Stack trace:
#0 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/tests/Phake/ClassGenerator/MockClassTest.php(818): PhakeTest_NullableScalarTypes_PHAKE593ffbdf3db3e1->objectReturn()
#1 [internal function]: Phake_ClassGenerator_MockClassTest->testStubbingNullableScalarReturnHints()
#2 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(987): ReflectionMethod->invokeArgs(Object(Phake_ClassGenerator_MockClassTest), Array)
#3 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/vendor/phpunit/phpunit/PHPUnit/Framework/TestCase.php(838): PHPUnit_Framework_TestCase->runTest()
#4 /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/vendor/phpunit/phpunit/PHPUnit/Framework/TestResult in /Users/t-kajinuma/.go/src/github.com/chocopie116/Phake/src/Phake/ClassGenerator/EvalLoader.php(58) : eval()'d code on line 56
zsh: exit 255   ./vendor/phpunit/phpunit/phpunit.php
```

**Comment by chocopie116** [comment]
Could you review?
@mlively

**Comment by mlively** [comment]
going to pull this branch over into and bring it up-to-date with master to make sure tests pass

**Comment by mlively** [comment]
Opened a new PR with an updated branch #247 , going to close this one

**Pull request closed without merging**
