### PR TITLE
make phake installable alongside with new phpunit6.2

### PR DESCRIPTION
**Pull request by fizzka**
need to test phake functionality with new sebastian/comparator dependency

### CODE REVIEW

**Comment by mlively** [comment]
This should be fine without this change now. Double check master, it can pull in phpunit 6.2 with no problem now.

**Comment by fizzka** [comment]
you're right. you mean I should use dev-master dependency in my configuration?

**Comment by mlively** [comment]
I actually just pushed it out as 3.0.0, so give it a few minutes and you can just update to that

**Comment by fizzka** [comment]
*cheers*

2017-07-04 23:23 GMT+03:00 Mike Lively <notifications@github.com>:

**Pull request closed without merging**
