### PR TITLE
Prevent constructor override when constructor is final

### PR DESCRIPTION
**Pull request by nicolasThal**
During my test, I wanted to mock a class with a final constructor like this one https://github.com/doctrine/annotations/blob/master/lib/Doctrine/Common/Annotations/Annotation.php which has a final constructor.

I have added a test for this case.

What are your thoughts about this issue?

Regards

### CODE REVIEW

**Comment by MaximeThoonsen** [comment]
+1

**Comment by juchi** [comment]
+1

**Comment by KennyDurand** [comment]
+1

**Comment by nicbaz** [comment]
:+1:

**Comment by jbeurel** [comment]
:+1:

**Comment by mlively** [comment]
I knew I was missing something :). Thanks

**Comment by mlively** [comment]
This is now available in v2.0.0-beta4 and v1.0.6

**Pull request merged**
