### PR TITLE
Add support for PHP8

### PR DESCRIPTION
**Pull request by adoy**
Hi,

This PR add support to PHP8 (and drop support for PHP<7.1). I'm not familiar at all with the Phake internal code so it's very much appreciated if you could have a look at this PR to make sure I did nothing wrong.

The quick steps that I did were :
- Change the tests to work on both phpunit 7.0 and 8.0
- Update doctrine/common to use ^3.0
- Add new `Phake_ClassGenerator_MockClass::implementType` method that support both named and union Types

I did test on my local on php7.1 php7.3 php7.4 and 8.0 and everything works fine.
I did not had the time to add more tests but feel free to add some or contribute to this PR :-)

Thanks

### CODE REVIEW

**Comment by adoy** [comment]
The build is failing but it also now fail on master :-/

**Comment by adoy** [comment]
This PR resolves #289 and also #284

**Comment by mlively** [comment]
It looks right, I don't really see anything new outside of the PHPUnit 8 and 9 integration pieces that wouldn't already be covered. I am not too worried about those, they are pretty basic and are essentially covered through the larger functional test.  Thank you! I'm going to merge it and look at a few test suites I have access to against it before I fully deploy to packagist.

**Review by mlively — APPROVED** [review]

**Comment by adoy** [comment]
Thanks a lot @mlively for the fast answer. Do you know how you want to release it ? Will it be a minor version bump ?

**Comment by mlively** [comment]
Because support for 7.0 is being removed, I'm inclined to make it a major version bump. So it'd be Phake 4.0.0.

**Comment by adoy** [comment]
Is this really a major ? Old projects will only stick to the old version but someone using like `^3.0` will still be working but will stick to the current version.

**Comment by mlively** [comment]
I'll think about it a little bit more while I run those tests. A very good argument is made in that link, but it's a bit of a shift from how I typically think about SemVer. So I just need to sort it out in my head.

Thanks for the link.

**Comment by adoy** [comment]
No worry :-) `4.0.0` is also ok with me ! Juste use the one you're more comfortable with ! If I can be of any help do not hesitate.

**Pull request merged**
